color: null
fieldLayouts:
  75ebe83c-b132-46b3-b498-6a30ce1da3c5:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-02-17T03:06:52+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 7851d02a-abcd-4754-8896-d197548e23b9
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: e5b52ba0-b2d5-4108-ac1c-9004e7e3d728
        userCondition: null
handle: body
hasTitleField: true
icon: null
name: Body
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
