color: cyan
fieldLayouts:
  1dbc13b6-56da-4009-ae3b-48619bb6262a:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-02-28T07:43:42+00:00'
            elementCondition: null
            fieldUid: d643786d-e7a9-4d3a-a1e9-64cd50dc0865 # Block Title
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dabb0e6d-44c6-4481-ab79-e815d3808b92
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-14T09:47:59+00:00'
            elementCondition: null
            fieldUid: 57b13ef5-778d-4dc5-937b-1d8d8c0944a0 # Description
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c654390d-3c73-41f1-9c08-e40e1469dc72
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-17T08:53:00+00:00'
            elementCondition: null
            fieldUid: 888140e3-670b-4481-aa4e-7eb5a4261e99 # Link Label
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 36e883a5-f0b4-48fa-bda7-a3419e381964
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-14T09:47:59+00:00'
            elementCondition: null
            fieldUid: f1788a9b-5962-4924-ad01-a4f2bdf1b5e3 # Action
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 79678f68-8559-4d48-9990-7cc6dcfde8f3
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-17T08:46:28+00:00'
            elementCondition: null
            fieldUid: 58b5afe0-1950-408f-8224-cb1d2d1bea68 # Features Cards
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e70e98af-227b-451f-9bfa-b660d73f5cd4
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 68f726c4-46bf-4877-a116-b3ae92633513
        userCondition: null
handle: features
hasTitleField: false
icon: icons
name: Features
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
