color: null
fieldLayouts:
  a9895604-0b7c-4aac-a158-814058a38bbd:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-02-17T08:43:04+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 42a8b2e7-c230-4604-9150-409164e6575d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-17T08:45:25+00:00'
            elementCondition: null
            fieldUid: fb9caff9-f9b6-405b-a495-283658dcd729 # Card Icon
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b290608b-083a-4a65-89ce-57991dc2c3dd
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-17T08:45:25+00:00'
            elementCondition: null
            fieldUid: 57b13ef5-778d-4dc5-937b-1d8d8c0944a0 # Description
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5cdd6d3c-1091-47c6-a5f3-0e91b202c612
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-17T09:06:58+00:00'
            elementCondition: null
            fieldUid: f1788a9b-5962-4924-ad01-a4f2bdf1b5e3 # Action
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 530345f6-2afa-4c3d-bd64-61b4edb47ab3
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 822ca971-a6f9-4cd8-a1c8-cd5c22312529
        userCondition: null
handle: feature
hasTitleField: true
icon: null
name: Feature
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
