color: cyan
fieldLayouts:
  a4e3c069-7963-4fcc-bf3f-3a3ab9aaaebd:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-02-18T05:26:26+00:00'
            elementCondition: null
            fieldUid: d643786d-e7a9-4d3a-a1e9-64cd50dc0865 # Block Title
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3caa98d4-5bca-41ab-bf5a-507a8a3d3191
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-18T05:26:26+00:00'
            elementCondition: null
            fieldUid: 57b13ef5-778d-4dc5-937b-1d8d8c0944a0 # Description
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5ed279bd-b277-4760-940b-d719e8e95523
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-18T05:26:26+00:00'
            elementCondition: null
            fieldUid: 3f660088-cf39-4fcf-b910-c6301a428916 # Letter
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 964d2c06-4401-40cd-bd25-f6ccd8d5e2f1
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 932ad922-3901-45fb-ab9a-3455c538d33b
        userCondition: null
handle: letter
hasTitleField: false
icon: envelope-open-text
name: Letter
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
