color: cyan
fieldLayouts:
  ce62e246-319a-4fa3-bef0-9ad438b6c9e6:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-02-18T09:10:57+00:00'
            elementCondition: null
            fieldUid: d643786d-e7a9-4d3a-a1e9-64cd50dc0865 # Block Title
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4b2958ad-1b70-418d-a9dd-bafb0c5c4845
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-18T09:10:57+00:00'
            elementCondition: null
            fieldUid: 57b13ef5-778d-4dc5-937b-1d8d8c0944a0 # Description
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 37c6b94e-8c64-42e9-bca4-1529a3074c81
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 27e1a534-f161-4fc6-b0ed-f59887626abc
        userCondition: null
handle: testimonialBlock
hasTitleField: false
icon: thought-bubble
name: 'Testimonial Block'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
