headingLevels:
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
name: Custom
options:
  alignment:
    options:
      - left
      - right
  allowedContent: true
  extraAllowedContent: 'span(*)'
toolbar:
  - heading
  - '|'
  - bold
  - numberedList
  - italic
  - bulletedList
  - alignment
  - underline
  - link
  - fontColor
  - code
