altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  3c2dc6bd-c19c-42c4-b56f-97964e102331:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-02-17T06:05:16+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 5a33f6a5-c058-4ef0-b751-290badf1aa3b
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: c24275b0-6781-48c0-8337-2e8dda1343bb
        userCondition: null
fs: uploads
handle: uploads
name: Uploads
sortOrder: 1
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
