columnSuffix: null
handle: backgroundColor
instructions: 'Select the checkbox if there is background color'
name: 'Background Color'
searchable: false
settings:
  customOptions: false
  options:
    -
      __assoc__:
        -
          - label
          - ''
        -
          - value
          - ''
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Checkboxes
