columnSuffix: null
handle: blockTitle
instructions: null
name: 'Block Title'
searchable: false
settings:
  availableTransforms: ''
  availableVolumes: '*'
  ckeConfig: null
  createButtonLabel: null
  defaultTransform: null
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  sourceEditingGroups:
    - __ADMINS__
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
