columnSuffix: null
handle: blogMainTitle
instructions: null
name: 'Blog Title'
searchable: false
settings:
  availableTransforms: ''
  availableVolumes: '*'
  ckeConfig: d72221be-33bf-4477-9a8e-00df49436e71 # h3 content only
  createButtonLabel: null
  defaultTransform: null
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  sourceEditingGroups:
    - __ADMINS__
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
