columnSuffix: null
handle: footerBottom
instructions: null
name: 'Footer Bottom'
searchable: false
settings:
  availableTransforms: ''
  availableVolumes: '*'
  ckeConfig: 735e60a0-6680-4f30-903b-3e29e330aa4d # Simple
  createButtonLabel: null
  defaultTransform: null
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  sourceEditingGroups:
    - __ADMINS__
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
