columnSuffix: null
handle: heroTitle
instructions: null
name: 'Hero Title'
searchable: false
settings:
  availableTransforms: ''
  availableVolumes: ''
  ckeConfig: 5680131d-c065-48f1-9768-1b7364cd1e6a # Custom
  createButtonLabel: null
  defaultTransform: null
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  sourceEditingGroups:
    - __ADMINS__
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
