columnSuffix: null
handle: letter
instructions: 'Write the letter.'
name: Letter
searchable: false
settings:
  availableTransforms: ''
  availableVolumes: '*'
  ckeConfig: null
  createButtonLabel: null
  defaultTransform: null
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  sourceEditingGroups:
    - __ADMINS__
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
