defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 2b370cdf-a912-4023-9118-3e32e4bc29dd # Index Page
handle: home
maxAuthors: 1
name: Home
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - /
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  480b27ed-ab52-4d46-9b4f-d4a706c3d3d8: # isgb
    enabledByDefault: true
    hasUrls: true
    template: index.twig
    uriFormat: __home__
type: single
